default:
  SECRET_KEY: "hard-to-guess-string"
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://fb_data:nLXirkxf6KPwLf5G@192.168.1.9/fb_data"
  AUTHORIZATION: "tt_w6XExU9klONzbsKWLxBCCTXsTAlx4nWs.487570ddc8474971a4e026f16ff4e5a0"

development:
  SECRET_KEY: "hard-to-guess-string"
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://fb_data:nLXirkxf6KPwLf5G@192.168.1.9/fb_data"
  AUTHORIZATION: "tt_w6XExU9klONzbsKWLxBCCTXsTAlx4nWs.487570ddc8474971a4e026f16ff4e5a0"

testing:
  SECRET_KEY: "hard-to-guess-string"
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://fb_data:nLXirkxf6KPwLf5G@192.168.1.9/fb_data"
  AUTHORIZATION: "tt_w6XExU9klONzbsKWLxBCCTXsTAlx4nWs.487570ddc8474971a4e026f16ff4e5a0"

production:
  SECRET_KEY: "hard-to-guess-string"
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://fb_data:cKZJWbfxRWm3hWEw@107.191.60.19/fb_data"
  AUTHORIZATION: "tt_w6XExU9klONzbsKWLxBCCTXsTAlx4nWs.487570ddc8474971a4e026f16ff4e5a0"
