default:
  SECRET_KEY: "hard-to-guess-string"
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://sportdata:KyFH3MyDcJ8aNztM@107.191.60.19/sportdata"
  SPIDER_URL: "http://example.com/data"
  AUTHORIZATION: "tt_6106zvDrksdzzTkXbABHIwEiApcTu6z2.3066f7f1ff252e1881f38f6a3c6e58ab"

development:
  DEBUG: true

testing:
  TESTING: true

production:
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://sportdata:KyFH3MyDcJ8aNztM@107.191.60.19/sportdata"
